### ISSUE TITLE
Status 404:file not found 

### ISSUE THREAD

**Issue by starloungeswitzerland** [amandris/arbitrage-trading-bot#15]
I have these error on console:

http://localhost:8000/bundles/fosjsrouting/js/router.js
file not found

Can't find variable "fos"

Can't find variable "Routing"

any solutions?

**Comment by amandris** [comment]
Did you get any error message when running `composer install` or `gulp`?

**Comment by starloungeswitzerland** [comment]
No, but I will try to reinstall...

**Comment by amandris** [comment]
Try with Node 10. My gulpfile.js is not ready for higher versions.

**Comment by starloungeswitzerland** [comment]
On reinstall, after running `composer install` and after prompt of values for `parameters.yml` I get this error:

_> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
Could not open input file: app/console
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception
                                                                             
[RuntimeException]                                                         
 An error occurred when executing the "'cache:clear --no-warmup'" command:  
                                                                             
  Could not open input file: app/console                                     
                                                                             

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]..._

And my note version is: **10.16.3**

**Comment by amandris** [comment]
Try to manually create the **var** directory into your project. Then run `composer install` again.

**Comment by starloungeswitzerland** [comment]
> Try to manually create the **var** directory into your project. Then run `composer install` again.

on the root?

**Comment by amandris** [comment]
Yes, on your project root.

**Comment by starloungeswitzerland** [comment]
Same error... if not reclone the repository.
All goes fine... many thanks.
